2018-03-04 12:30:41.493 [error] <0.197.0>@Elixir.Logger.Watcher:init:25 CRASH REPORT Process <0.197.0> with 0 neighbours crashed with reason: no case clause matching {'EXIT',{function_clause,[{'Elixir.Keyword',get,[nil,level,nil],[{file,"lib/keyword.ex"},{line,179}]},{'Elixir.LagerBackend',init,2,[{file,"lib/lager_backend.ex"},{line,52}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,14}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in 'Elixir.Logger.Watcher':init/1 line 25
2018-03-04 12:30:41.494 [error] <0.193.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.WatcherSupervisor' started with 'Elixir.Logger.WatcherSupervisor':start_link({'Elixir.Logger.Config',handlers,[]}) at undefined exit with reason {'EXIT',{{badmatch,{error,{{{case_clause,{'EXIT',{function_clause,[{'Elixir.Keyword',get,[nil,level,nil],[{file,"lib/keyword.ex"},{line,179}]},{'Elixir.LagerBackend',init,2,[{file,"lib/lager_backend.ex"},{line,52}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,14}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},[{'Elixir.Logger.Watcher',...},...]},...}}},...}} in context start_error
2018-03-04 12:33:54.474 [error] <0.179.0>@Elixir.Logger.Watcher:init:25 CRASH REPORT Process <0.179.0> with 0 neighbours crashed with reason: no case clause matching {'EXIT',{function_clause,[{'Elixir.Keyword',get,[nil,level,nil],[{file,"lib/keyword.ex"},{line,179}]},{'Elixir.LagerBackend',init,2,[{file,"lib/lager_backend.ex"},{line,53}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,14}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in 'Elixir.Logger.Watcher':init/1 line 25
2018-03-04 12:33:54.477 [error] <0.175.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.WatcherSupervisor' started with 'Elixir.Logger.WatcherSupervisor':start_link({'Elixir.Logger.Config',handlers,[]}) at undefined exit with reason {'EXIT',{{badmatch,{error,{{{case_clause,{'EXIT',{function_clause,[{'Elixir.Keyword',get,[nil,level,nil],[{file,"lib/keyword.ex"},{line,179}]},{'Elixir.LagerBackend',init,2,[{file,"lib/lager_backend.ex"},{line,53}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,14}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},[{'Elixir.Logger.Watcher',...},...]},...}}},...}} in context start_error
2018-03-04 12:33:54.477 [error] <0.173.0> CRASH REPORT Process <0.173.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Logger.WatcherSupervisor',{'EXIT',{{badmatch,{error,{{{case_clause,{'EXIT',{function_clause,[{'Elixir.Keyword',get,[nil,level,nil],[{file,"lib/keyword.ex"},{line,179}]},{'Elixir.LagerBackend',init,2,[{file,"lib/lager_backend.ex"},{line,53}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,14}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,...}]}}},...},...}}},...}}}},...} in application_master:init/4 line 134
2018-03-04 12:35:01.791 [error] <0.179.0>@Elixir.Logger.Watcher:init:25 CRASH REPORT Process <0.179.0> with 0 neighbours crashed with reason: no case clause matching {'EXIT',{function_clause,[{'Elixir.LagerBackend',init,[[]],[{file,"lib/lager_backend.ex"},{line,12}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,14}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in 'Elixir.Logger.Watcher':init/1 line 25
2018-03-04 12:35:01.796 [error] <0.175.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.WatcherSupervisor' started with 'Elixir.Logger.WatcherSupervisor':start_link({'Elixir.Logger.Config',handlers,[]}) at undefined exit with reason {'EXIT',{{badmatch,{error,{{{case_clause,{'EXIT',{function_clause,[{'Elixir.LagerBackend',init,[[]],[{file,"lib/lager_backend.ex"},{line,12}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,14}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},[{'Elixir.Logger.Watcher',init,1,[{file,"lib/logger/watcher.ex"},{line,25}]},{gen_server,...},...]},...}}},...}} in context start_error
2018-03-04 12:35:01.796 [error] <0.173.0> CRASH REPORT Process <0.173.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Logger.WatcherSupervisor',{'EXIT',{{badmatch,{error,{{{case_clause,{'EXIT',{function_clause,[{'Elixir.LagerBackend',init,[[]],[{file,"lib/lager_backend.ex"},{line,12}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,14}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},[{'Elixir.Logger.Watcher',...},...]},...}}},...}}}},...} in application_master:init/4 line 134
2018-03-04 12:36:27.248 [error] <0.179.0>@Elixir.Logger.Watcher:init:25 CRASH REPORT Process <0.179.0> with 0 neighbours crashed with reason: no case clause matching {'EXIT',{function_clause,[{'Elixir.LagerBackend',init,[[]],[{file,"lib/lager_backend.ex"},{line,12}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,14}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in 'Elixir.Logger.Watcher':init/1 line 25
2018-03-04 12:36:27.253 [error] <0.175.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.WatcherSupervisor' started with 'Elixir.Logger.WatcherSupervisor':start_link({'Elixir.Logger.Config',handlers,[]}) at undefined exit with reason {'EXIT',{{badmatch,{error,{{{case_clause,{'EXIT',{function_clause,[{'Elixir.LagerBackend',init,[[]],[{file,"lib/lager_backend.ex"},{line,12}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,14}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},[{'Elixir.Logger.Watcher',init,1,[{file,"lib/logger/watcher.ex"},{line,25}]},{gen_server,...},...]},...}}},...}} in context start_error
2018-03-04 12:36:27.253 [error] <0.173.0> CRASH REPORT Process <0.173.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Logger.WatcherSupervisor',{'EXIT',{{badmatch,{error,{{{case_clause,{'EXIT',{function_clause,[{'Elixir.LagerBackend',init,[[]],[{file,"lib/lager_backend.ex"},{line,12}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,14}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},[{'Elixir.Logger.Watcher',...},...]},...}}},...}}}},...} in application_master:init/4 line 134
2018-03-04 12:37:43.850 [error] <0.179.0>@Elixir.Logger.Watcher:init:25 CRASH REPORT Process <0.179.0> with 0 neighbours crashed with reason: no case clause matching {'EXIT',{function_clause,[{'Elixir.LagerBackend',init,[[]],[{file,"lib/lager_backend.ex"},{line,12}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,15}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in 'Elixir.Logger.Watcher':init/1 line 25
2018-03-04 12:37:43.855 [error] <0.175.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.WatcherSupervisor' started with 'Elixir.Logger.WatcherSupervisor':start_link({'Elixir.Logger.Config',handlers,[]}) at undefined exit with reason {'EXIT',{{badmatch,{error,{{{case_clause,{'EXIT',{function_clause,[{'Elixir.LagerBackend',init,[[]],[{file,"lib/lager_backend.ex"},{line,12}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,15}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},[{'Elixir.Logger.Watcher',init,1,[{file,"lib/logger/watcher.ex"},{line,25}]},{gen_server,...},...]},...}}},...}} in context start_error
2018-03-04 12:37:43.855 [error] <0.173.0> CRASH REPORT Process <0.173.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Logger.WatcherSupervisor',{'EXIT',{{badmatch,{error,{{{case_clause,{'EXIT',{function_clause,[{'Elixir.LagerBackend',init,[[]],[{file,"lib/lager_backend.ex"},{line,12}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,15}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},[{'Elixir.Logger.Watcher',...},...]},...}}},...}}}},...} in application_master:init/4 line 134
2018-03-04 12:39:41.733 [error] <0.179.0>@Elixir.Logger.Watcher:init:25 CRASH REPORT Process <0.179.0> with 0 neighbours crashed with reason: no case clause matching {'EXIT',{function_clause,[{'Elixir.LagerBackend',init,[[]],[{file,"lib/lager_backend.ex"},{line,12}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,15}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in 'Elixir.Logger.Watcher':init/1 line 25
2018-03-04 12:39:41.739 [error] <0.175.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.WatcherSupervisor' started with 'Elixir.Logger.WatcherSupervisor':start_link({'Elixir.Logger.Config',handlers,[]}) at undefined exit with reason {'EXIT',{{badmatch,{error,{{{case_clause,{'EXIT',{function_clause,[{'Elixir.LagerBackend',init,[[]],[{file,"lib/lager_backend.ex"},{line,12}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,15}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},[{'Elixir.Logger.Watcher',init,1,[{file,"lib/logger/watcher.ex"},{line,25}]},{gen_server,...},...]},...}}},...}} in context start_error
2018-03-04 12:39:41.739 [error] <0.173.0> CRASH REPORT Process <0.173.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Logger.WatcherSupervisor',{'EXIT',{{badmatch,{error,{{{case_clause,{'EXIT',{function_clause,[{'Elixir.LagerBackend',init,[[]],[{file,"lib/lager_backend.ex"},{line,12}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,15}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},[{'Elixir.Logger.Watcher',...},...]},...}}},...}}}},...} in application_master:init/4 line 134
2018-03-04 12:40:06.460 [error] <0.179.0>@Elixir.Logger.Watcher:init:25 CRASH REPORT Process <0.179.0> with 0 neighbours crashed with reason: no case clause matching {'EXIT',{function_clause,[{'Elixir.LagerBackend',init,[[]],[{file,"lib/lager_backend.ex"},{line,12}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,17}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in 'Elixir.Logger.Watcher':init/1 line 25
2018-03-04 12:40:06.465 [error] <0.175.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.WatcherSupervisor' started with 'Elixir.Logger.WatcherSupervisor':start_link({'Elixir.Logger.Config',handlers,[]}) at undefined exit with reason {'EXIT',{{badmatch,{error,{{{case_clause,{'EXIT',{function_clause,[{'Elixir.LagerBackend',init,[[]],[{file,"lib/lager_backend.ex"},{line,12}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,17}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},[{'Elixir.Logger.Watcher',init,1,[{file,"lib/logger/watcher.ex"},{line,25}]},{gen_server,...},...]},...}}},...}} in context start_error
2018-03-04 12:40:06.465 [error] <0.173.0> CRASH REPORT Process <0.173.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Logger.WatcherSupervisor',{'EXIT',{{badmatch,{error,{{{case_clause,{'EXIT',{function_clause,[{'Elixir.LagerBackend',init,[[]],[{file,"lib/lager_backend.ex"},{line,12}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,17}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},[{'Elixir.Logger.Watcher',...},...]},...}}},...}}}},...} in application_master:init/4 line 134
2018-03-04 12:42:40.525 [error] <0.179.0>@Elixir.Logger.Watcher:init:25 CRASH REPORT Process <0.179.0> with 0 neighbours crashed with reason: no case clause matching {'EXIT',{function_clause,[{'Elixir.LagerBackend',init,[[]],[{file,"lib/lager_backend.ex"},{line,12}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,17}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in 'Elixir.Logger.Watcher':init/1 line 25
2018-03-04 12:42:40.530 [error] <0.175.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.WatcherSupervisor' started with 'Elixir.Logger.WatcherSupervisor':start_link({'Elixir.Logger.Config',handlers,[]}) at undefined exit with reason {'EXIT',{{badmatch,{error,{{{case_clause,{'EXIT',{function_clause,[{'Elixir.LagerBackend',init,[[]],[{file,"lib/lager_backend.ex"},{line,12}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,17}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},[{'Elixir.Logger.Watcher',init,1,[{file,"lib/logger/watcher.ex"},{line,25}]},{gen_server,...},...]},...}}},...}} in context start_error
2018-03-04 12:42:40.530 [error] <0.173.0> CRASH REPORT Process <0.173.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Logger.WatcherSupervisor',{'EXIT',{{badmatch,{error,{{{case_clause,{'EXIT',{function_clause,[{'Elixir.LagerBackend',init,[[]],[{file,"lib/lager_backend.ex"},{line,12}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,17}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},[{'Elixir.Logger.Watcher',...},...]},...}}},...}}}},...} in application_master:init/4 line 134
2018-03-04 12:44:13.785 [error] <0.179.0>@Elixir.Logger.Watcher:init:25 CRASH REPORT Process <0.179.0> with 0 neighbours crashed with reason: no case clause matching {'EXIT',{function_clause,[{'Elixir.LagerBackend',init,[[]],[{file,"lib/lager_backend.ex"},{line,12}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,17}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in 'Elixir.Logger.Watcher':init/1 line 25
2018-03-04 12:44:13.790 [error] <0.175.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.WatcherSupervisor' started with 'Elixir.Logger.WatcherSupervisor':start_link({'Elixir.Logger.Config',handlers,[]}) at undefined exit with reason {'EXIT',{{badmatch,{error,{{{case_clause,{'EXIT',{function_clause,[{'Elixir.LagerBackend',init,[[]],[{file,"lib/lager_backend.ex"},{line,12}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,17}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},[{'Elixir.Logger.Watcher',init,1,[{file,"lib/logger/watcher.ex"},{line,25}]},{gen_server,...},...]},...}}},...}} in context start_error
2018-03-04 12:44:13.790 [error] <0.173.0> CRASH REPORT Process <0.173.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Logger.WatcherSupervisor',{'EXIT',{{badmatch,{error,{{{case_clause,{'EXIT',{function_clause,[{'Elixir.LagerBackend',init,[[]],[{file,"lib/lager_backend.ex"},{line,12}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,17}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},[{'Elixir.Logger.Watcher',...},...]},...}}},...}}}},...} in application_master:init/4 line 134
2018-03-04 12:44:25.082 [error] <0.170.0>@Elixir.Logger.Watcher:init:25 CRASH REPORT Process <0.170.0> with 0 neighbours crashed with reason: no case clause matching {'EXIT',{function_clause,[{'Elixir.LagerBackend',init,[[]],[{file,"lib/lager_backend.ex"},{line,12}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,17}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in 'Elixir.Logger.Watcher':init/1 line 25
2018-03-04 12:44:25.086 [error] <0.166.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.WatcherSupervisor' started with 'Elixir.Logger.WatcherSupervisor':start_link({'Elixir.Logger.Config',handlers,[]}) at undefined exit with reason {'EXIT',{{badmatch,{error,{{{case_clause,{'EXIT',{function_clause,[{'Elixir.LagerBackend',init,[[]],[{file,"lib/lager_backend.ex"},{line,12}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,17}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},[{'Elixir.Logger.Watcher',init,1,[{file,"lib/logger/watcher.ex"},{line,25}]},{gen_server,...},...]},...}}},...}} in context start_error
2018-03-04 12:44:25.086 [error] <0.164.0> CRASH REPORT Process <0.164.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Logger.WatcherSupervisor',{'EXIT',{{badmatch,{error,{{{case_clause,{'EXIT',{function_clause,[{'Elixir.LagerBackend',init,[[]],[{file,"lib/lager_backend.ex"},{line,12}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,17}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},[{'Elixir.Logger.Watcher',...},...]},...}}},...}}}},...} in application_master:init/4 line 134
2018-03-04 12:45:03.865 [error] <0.179.0>@Elixir.Logger.Watcher:init:25 CRASH REPORT Process <0.179.0> with 0 neighbours crashed with reason: no case clause matching {'EXIT',{function_clause,[{'Elixir.LagerBackend',init,[[]],[{file,"lib/lager_backend.ex"},{line,12}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,18}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in 'Elixir.Logger.Watcher':init/1 line 25
2018-03-04 12:45:03.869 [error] <0.175.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.WatcherSupervisor' started with 'Elixir.Logger.WatcherSupervisor':start_link({'Elixir.Logger.Config',handlers,[]}) at undefined exit with reason {'EXIT',{{badmatch,{error,{{{case_clause,{'EXIT',{function_clause,[{'Elixir.LagerBackend',init,[[]],[{file,"lib/lager_backend.ex"},{line,12}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,18}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},[{'Elixir.Logger.Watcher',init,1,[{file,"lib/logger/watcher.ex"},{line,25}]},{gen_server,...},...]},...}}},...}} in context start_error
2018-03-04 12:45:03.869 [error] <0.173.0> CRASH REPORT Process <0.173.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Logger.WatcherSupervisor',{'EXIT',{{badmatch,{error,{{{case_clause,{'EXIT',{function_clause,[{'Elixir.LagerBackend',init,[[]],[{file,"lib/lager_backend.ex"},{line,12}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,18}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},[{'Elixir.Logger.Watcher',...},...]},...}}},...}}}},...} in application_master:init/4 line 134
2018-03-04 13:19:29.750 [error] <0.179.0>@Elixir.Logger.Watcher:init:25 CRASH REPORT Process <0.179.0> with 0 neighbours crashed with reason: no case clause matching {'EXIT',{function_clause,[{'Elixir.IO',inspect,[stdio,nil,#{'__struct__' => 'Elixir.LagerBackend',format => nil,level => nil,metadata => nil}],[{file,"lib/io.ex"},{line,305}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,19}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in 'Elixir.Logger.Watcher':init/1 line 25
2018-03-04 13:19:29.752 [error] <0.175.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.WatcherSupervisor' started with 'Elixir.Logger.WatcherSupervisor':start_link({'Elixir.Logger.Config',handlers,[]}) at undefined exit with reason {'EXIT',{{badmatch,{error,{{{case_clause,{'EXIT',{function_clause,[{'Elixir.IO',inspect,[stdio,nil,#{'__struct__' => 'Elixir.LagerBackend',format => nil,level => nil,metadata => nil}],[{file,"lib/io.ex"},{line,305}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,19}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},[{'Elixir.Logger.Watcher',...},...]},...}}},...}} in context start_error
2018-03-04 13:19:29.753 [error] <0.173.0> CRASH REPORT Process <0.173.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Logger.WatcherSupervisor',{'EXIT',{{badmatch,{error,{{{case_clause,{'EXIT',{function_clause,[{'Elixir.IO',inspect,[stdio,nil,#{'__struct__' => 'Elixir.LagerBackend',format => nil,level => nil,metadata => nil}],[{file,"lib/io.ex"},{line,305}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,19}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,...}]}}},...},...}}},...}}}},...} in application_master:init/4 line 134
2018-03-04 13:20:08.366 [error] <0.179.0>@Elixir.Logger.Watcher:init:25 CRASH REPORT Process <0.179.0> with 0 neighbours crashed with reason: no case clause matching {'EXIT',{function_clause,[{'Elixir.LagerBackend',init,[[]],[{file,"lib/lager_backend.ex"},{line,12}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,20}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in 'Elixir.Logger.Watcher':init/1 line 25
2018-03-04 13:20:08.369 [error] <0.175.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.WatcherSupervisor' started with 'Elixir.Logger.WatcherSupervisor':start_link({'Elixir.Logger.Config',handlers,[]}) at undefined exit with reason {'EXIT',{{badmatch,{error,{{{case_clause,{'EXIT',{function_clause,[{'Elixir.LagerBackend',init,[[]],[{file,"lib/lager_backend.ex"},{line,12}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,20}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},[{'Elixir.Logger.Watcher',init,1,[{file,"lib/logger/watcher.ex"},{line,25}]},{gen_server,...},...]},...}}},...}} in context start_error
2018-03-04 13:20:08.369 [error] <0.173.0> CRASH REPORT Process <0.173.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Logger.WatcherSupervisor',{'EXIT',{{badmatch,{error,{{{case_clause,{'EXIT',{function_clause,[{'Elixir.LagerBackend',init,[[]],[{file,"lib/lager_backend.ex"},{line,12}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,20}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},[{'Elixir.Logger.Watcher',...},...]},...}}},...}}}},...} in application_master:init/4 line 134
2018-03-04 13:20:54.557 [error] <0.179.0>@Elixir.Logger.Watcher:init:25 CRASH REPORT Process <0.179.0> with 0 neighbours crashed with reason: no case clause matching {'EXIT',{function_clause,[{'Elixir.LagerBackend',init,[[]],[{file,"lib/lager_backend.ex"},{line,12}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,20}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in 'Elixir.Logger.Watcher':init/1 line 25
2018-03-04 13:20:54.560 [error] <0.175.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.WatcherSupervisor' started with 'Elixir.Logger.WatcherSupervisor':start_link({'Elixir.Logger.Config',handlers,[]}) at undefined exit with reason {'EXIT',{{badmatch,{error,{{{case_clause,{'EXIT',{function_clause,[{'Elixir.LagerBackend',init,[[]],[{file,"lib/lager_backend.ex"},{line,12}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,20}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},[{'Elixir.Logger.Watcher',init,1,[{file,"lib/logger/watcher.ex"},{line,25}]},{gen_server,...},...]},...}}},...}} in context start_error
2018-03-04 13:20:54.560 [error] <0.173.0> CRASH REPORT Process <0.173.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Logger.WatcherSupervisor',{'EXIT',{{badmatch,{error,{{{case_clause,{'EXIT',{function_clause,[{'Elixir.LagerBackend',init,[[]],[{file,"lib/lager_backend.ex"},{line,12}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,20}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},[{'Elixir.Logger.Watcher',...},...]},...}}},...}}}},...} in application_master:init/4 line 134
2018-03-04 13:22:31.709 [error] <0.179.0>@Elixir.Logger.Watcher:init:25 CRASH REPORT Process <0.179.0> with 0 neighbours crashed with reason: no case clause matching {'EXIT',{function_clause,[{'Elixir.LagerBackend',init,[[]],[{file,"lib/lager_backend.ex"},{line,12}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,20}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in 'Elixir.Logger.Watcher':init/1 line 25
2018-03-04 13:22:31.711 [error] <0.175.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.WatcherSupervisor' started with 'Elixir.Logger.WatcherSupervisor':start_link({'Elixir.Logger.Config',handlers,[]}) at undefined exit with reason {'EXIT',{{badmatch,{error,{{{case_clause,{'EXIT',{function_clause,[{'Elixir.LagerBackend',init,[[]],[{file,"lib/lager_backend.ex"},{line,12}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,20}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},[{'Elixir.Logger.Watcher',init,1,[{file,"lib/logger/watcher.ex"},{line,25}]},{gen_server,...},...]},...}}},...}} in context start_error
2018-03-04 13:22:31.712 [error] <0.173.0> CRASH REPORT Process <0.173.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Logger.WatcherSupervisor',{'EXIT',{{badmatch,{error,{{{case_clause,{'EXIT',{function_clause,[{'Elixir.LagerBackend',init,[[]],[{file,"lib/lager_backend.ex"},{line,12}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,20}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},[{'Elixir.Logger.Watcher',...},...]},...}}},...}}}},...} in application_master:init/4 line 134
2018-03-04 13:22:46.345 [error] <0.179.0>@Elixir.Logger.Watcher:init:25 CRASH REPORT Process <0.179.0> with 0 neighbours crashed with reason: no case clause matching {'EXIT',{function_clause,[{'Elixir.LagerBackend',init,[[]],[{file,"lib/lager_backend.ex"},{line,12}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,20}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in 'Elixir.Logger.Watcher':init/1 line 25
2018-03-04 13:22:46.348 [error] <0.175.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.WatcherSupervisor' started with 'Elixir.Logger.WatcherSupervisor':start_link({'Elixir.Logger.Config',handlers,[]}) at undefined exit with reason {'EXIT',{{badmatch,{error,{{{case_clause,{'EXIT',{function_clause,[{'Elixir.LagerBackend',init,[[]],[{file,"lib/lager_backend.ex"},{line,12}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,20}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},[{'Elixir.Logger.Watcher',init,1,[{file,"lib/logger/watcher.ex"},{line,25}]},{gen_server,...},...]},...}}},...}} in context start_error
2018-03-04 13:22:46.348 [error] <0.173.0> CRASH REPORT Process <0.173.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Logger.WatcherSupervisor',{'EXIT',{{badmatch,{error,{{{case_clause,{'EXIT',{function_clause,[{'Elixir.LagerBackend',init,[[]],[{file,"lib/lager_backend.ex"},{line,12}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,20}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},[{'Elixir.Logger.Watcher',...},...]},...}}},...}}}},...} in application_master:init/4 line 134
2018-03-04 13:23:01.451 [error] <0.179.0>@Elixir.Logger.Watcher:init:25 CRASH REPORT Process <0.179.0> with 0 neighbours crashed with reason: no case clause matching {'EXIT',{function_clause,[{'Elixir.LagerBackend',init,[[]],[{file,"lib/lager_backend.ex"},{line,12}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,24}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in 'Elixir.Logger.Watcher':init/1 line 25
2018-03-04 13:23:01.453 [error] <0.175.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.WatcherSupervisor' started with 'Elixir.Logger.WatcherSupervisor':start_link({'Elixir.Logger.Config',handlers,[]}) at undefined exit with reason {'EXIT',{{badmatch,{error,{{{case_clause,{'EXIT',{function_clause,[{'Elixir.LagerBackend',init,[[]],[{file,"lib/lager_backend.ex"},{line,12}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,24}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},[{'Elixir.Logger.Watcher',init,1,[{file,"lib/logger/watcher.ex"},{line,25}]},{gen_server,...},...]},...}}},...}} in context start_error
2018-03-04 13:23:01.453 [error] <0.173.0> CRASH REPORT Process <0.173.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Logger.WatcherSupervisor',{'EXIT',{{badmatch,{error,{{{case_clause,{'EXIT',{function_clause,[{'Elixir.LagerBackend',init,[[]],[{file,"lib/lager_backend.ex"},{line,12}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,24}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},[{'Elixir.Logger.Watcher',...},...]},...}}},...}}}},...} in application_master:init/4 line 134
2018-03-04 13:24:40.110 [error] <0.179.0>@Elixir.Logger.Watcher:init:25 CRASH REPORT Process <0.179.0> with 0 neighbours crashed with reason: no case clause matching {'EXIT',{function_clause,[{'Elixir.Keyword',get,[nil,level,nil],[{file,"lib/keyword.ex"},{line,179}]},{'Elixir.LagerBackend',foo,2,[{file,"lib/lager_backend.ex"},{line,72}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,22}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in 'Elixir.Logger.Watcher':init/1 line 25
2018-03-04 13:24:40.112 [error] <0.175.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.WatcherSupervisor' started with 'Elixir.Logger.WatcherSupervisor':start_link({'Elixir.Logger.Config',handlers,[]}) at undefined exit with reason {'EXIT',{{badmatch,{error,{{{case_clause,{'EXIT',{function_clause,[{'Elixir.Keyword',get,[nil,level,nil],[{file,"lib/keyword.ex"},{line,179}]},{'Elixir.LagerBackend',foo,2,[{file,"lib/lager_backend.ex"},{line,72}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,22}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},[{'Elixir.Logger.Watcher',...},...]},...}}},...}} in context start_error
2018-03-04 13:24:40.112 [error] <0.173.0> CRASH REPORT Process <0.173.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Logger.WatcherSupervisor',{'EXIT',{{badmatch,{error,{{{case_clause,{'EXIT',{function_clause,[{'Elixir.Keyword',get,[nil,level,nil],[{file,"lib/keyword.ex"},{line,179}]},{'Elixir.LagerBackend',foo,2,[{file,"lib/lager_backend.ex"},{line,72}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,22}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,...}]}}},...},...}}},...}}}},...} in application_master:init/4 line 134
2018-03-04 13:25:13.295 [error] <0.179.0>@Elixir.Logger.Watcher:init:25 CRASH REPORT Process <0.179.0> with 0 neighbours crashed with reason: no case clause matching {'EXIT',{function_clause,[{'Elixir.Keyword',get,[nil,level,nil],[{file,"lib/keyword.ex"},{line,179}]},{'Elixir.LagerBackend',foo,2,[{file,"lib/lager_backend.ex"},{line,72}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,22}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in 'Elixir.Logger.Watcher':init/1 line 25
2018-03-04 13:25:13.297 [error] <0.175.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.WatcherSupervisor' started with 'Elixir.Logger.WatcherSupervisor':start_link({'Elixir.Logger.Config',handlers,[]}) at undefined exit with reason {'EXIT',{{badmatch,{error,{{{case_clause,{'EXIT',{function_clause,[{'Elixir.Keyword',get,[nil,level,nil],[{file,"lib/keyword.ex"},{line,179}]},{'Elixir.LagerBackend',foo,2,[{file,"lib/lager_backend.ex"},{line,72}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,22}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},[{'Elixir.Logger.Watcher',...},...]},...}}},...}} in context start_error
2018-03-04 13:25:13.297 [error] <0.173.0> CRASH REPORT Process <0.173.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Logger.WatcherSupervisor',{'EXIT',{{badmatch,{error,{{{case_clause,{'EXIT',{function_clause,[{'Elixir.Keyword',get,[nil,level,nil],[{file,"lib/keyword.ex"},{line,179}]},{'Elixir.LagerBackend',foo,2,[{file,"lib/lager_backend.ex"},{line,72}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,22}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,...}]}}},...},...}}},...}}}},...} in application_master:init/4 line 134
2018-03-04 13:25:20.888 [error] <0.170.0>@Elixir.Logger.Watcher:init:25 CRASH REPORT Process <0.170.0> with 0 neighbours crashed with reason: no case clause matching {'EXIT',{function_clause,[{'Elixir.Keyword',get,[nil,level,nil],[{file,"lib/keyword.ex"},{line,179}]},{'Elixir.LagerBackend',foo,2,[{file,"lib/lager_backend.ex"},{line,72}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,22}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in 'Elixir.Logger.Watcher':init/1 line 25
2018-03-04 13:25:20.890 [error] <0.166.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.WatcherSupervisor' started with 'Elixir.Logger.WatcherSupervisor':start_link({'Elixir.Logger.Config',handlers,[]}) at undefined exit with reason {'EXIT',{{badmatch,{error,{{{case_clause,{'EXIT',{function_clause,[{'Elixir.Keyword',get,[nil,level,nil],[{file,"lib/keyword.ex"},{line,179}]},{'Elixir.LagerBackend',foo,2,[{file,"lib/lager_backend.ex"},{line,72}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,22}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},[{'Elixir.Logger.Watcher',...},...]},...}}},...}} in context start_error
2018-03-04 13:25:20.890 [error] <0.164.0> CRASH REPORT Process <0.164.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Logger.WatcherSupervisor',{'EXIT',{{badmatch,{error,{{{case_clause,{'EXIT',{function_clause,[{'Elixir.Keyword',get,[nil,level,nil],[{file,"lib/keyword.ex"},{line,179}]},{'Elixir.LagerBackend',foo,2,[{file,"lib/lager_backend.ex"},{line,72}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,22}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,...}]}}},...},...}}},...}}}},...} in application_master:init/4 line 134
2018-03-04 13:26:10.709 [error] <0.179.0>@Elixir.Logger.Watcher:init:25 CRASH REPORT Process <0.179.0> with 0 neighbours crashed with reason: no case clause matching {'EXIT',{function_clause,[{'Elixir.Keyword',get,[nil,level,nil],[{file,"lib/keyword.ex"},{line,179}]},{'Elixir.LagerBackend',foo,2,[{file,"lib/lager_backend.ex"},{line,73}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,22}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in 'Elixir.Logger.Watcher':init/1 line 25
2018-03-04 13:26:10.711 [error] <0.175.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.WatcherSupervisor' started with 'Elixir.Logger.WatcherSupervisor':start_link({'Elixir.Logger.Config',handlers,[]}) at undefined exit with reason {'EXIT',{{badmatch,{error,{{{case_clause,{'EXIT',{function_clause,[{'Elixir.Keyword',get,[nil,level,nil],[{file,"lib/keyword.ex"},{line,179}]},{'Elixir.LagerBackend',foo,2,[{file,"lib/lager_backend.ex"},{line,73}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,22}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},[{'Elixir.Logger.Watcher',...},...]},...}}},...}} in context start_error
2018-03-04 13:26:10.711 [error] <0.173.0> CRASH REPORT Process <0.173.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Logger.WatcherSupervisor',{'EXIT',{{badmatch,{error,{{{case_clause,{'EXIT',{function_clause,[{'Elixir.Keyword',get,[nil,level,nil],[{file,"lib/keyword.ex"},{line,179}]},{'Elixir.LagerBackend',foo,2,[{file,"lib/lager_backend.ex"},{line,73}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,22}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,...}]}}},...},...}}},...}}}},...} in application_master:init/4 line 134
2018-03-04 13:26:56.003 [error] <0.179.0>@Elixir.Logger.Watcher:init:25 CRASH REPORT Process <0.179.0> with 0 neighbours crashed with reason: no case clause matching {'EXIT',{function_clause,[{'Elixir.LagerBackend',init,[[]],[{file,"lib/lager_backend.ex"},{line,12}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,24}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in 'Elixir.Logger.Watcher':init/1 line 25
2018-03-04 13:26:56.006 [error] <0.175.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.WatcherSupervisor' started with 'Elixir.Logger.WatcherSupervisor':start_link({'Elixir.Logger.Config',handlers,[]}) at undefined exit with reason {'EXIT',{{badmatch,{error,{{{case_clause,{'EXIT',{function_clause,[{'Elixir.LagerBackend',init,[[]],[{file,"lib/lager_backend.ex"},{line,12}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,24}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},[{'Elixir.Logger.Watcher',init,1,[{file,"lib/logger/watcher.ex"},{line,25}]},{gen_server,...},...]},...}}},...}} in context start_error
2018-03-04 13:26:56.006 [error] <0.173.0> CRASH REPORT Process <0.173.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Logger.WatcherSupervisor',{'EXIT',{{badmatch,{error,{{{case_clause,{'EXIT',{function_clause,[{'Elixir.LagerBackend',init,[[]],[{file,"lib/lager_backend.ex"},{line,12}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,24}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},[{'Elixir.Logger.Watcher',...},...]},...}}},...}}}},...} in application_master:init/4 line 134
2018-03-04 13:27:59.395 [error] <0.179.0>@Elixir.Logger.Watcher:init:25 CRASH REPORT Process <0.179.0> with 0 neighbours crashed with reason: no case clause matching {'EXIT',{function_clause,[{'Elixir.LagerBackend',init,[[]],[{file,"lib/lager_backend.ex"},{line,12}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,24}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in 'Elixir.Logger.Watcher':init/1 line 25
2018-03-04 13:27:59.398 [error] <0.175.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.WatcherSupervisor' started with 'Elixir.Logger.WatcherSupervisor':start_link({'Elixir.Logger.Config',handlers,[]}) at undefined exit with reason {'EXIT',{{badmatch,{error,{{{case_clause,{'EXIT',{function_clause,[{'Elixir.LagerBackend',init,[[]],[{file,"lib/lager_backend.ex"},{line,12}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,24}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},[{'Elixir.Logger.Watcher',init,1,[{file,"lib/logger/watcher.ex"},{line,25}]},{gen_server,...},...]},...}}},...}} in context start_error
2018-03-04 13:27:59.398 [error] <0.173.0> CRASH REPORT Process <0.173.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Logger.WatcherSupervisor',{'EXIT',{{badmatch,{error,{{{case_clause,{'EXIT',{function_clause,[{'Elixir.LagerBackend',init,[[]],[{file,"lib/lager_backend.ex"},{line,12}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,24}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},[{'Elixir.Logger.Watcher',...},...]},...}}},...}}}},...} in application_master:init/4 line 134
2018-03-04 13:28:39.287 [error] <0.179.0>@Elixir.Logger.Watcher:init:25 CRASH REPORT Process <0.179.0> with 0 neighbours crashed with reason: no case clause matching {'EXIT',{function_clause,[{'Elixir.LagerBackend',init,[[]],[{file,"lib/lager_backend.ex"},{line,12}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,24}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in 'Elixir.Logger.Watcher':init/1 line 25
2018-03-04 13:28:39.290 [error] <0.175.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.WatcherSupervisor' started with 'Elixir.Logger.WatcherSupervisor':start_link({'Elixir.Logger.Config',handlers,[]}) at undefined exit with reason {'EXIT',{{badmatch,{error,{{{case_clause,{'EXIT',{function_clause,[{'Elixir.LagerBackend',init,[[]],[{file,"lib/lager_backend.ex"},{line,12}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,24}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},[{'Elixir.Logger.Watcher',init,1,[{file,"lib/logger/watcher.ex"},{line,25}]},{gen_server,...},...]},...}}},...}} in context start_error
2018-03-04 13:28:39.290 [error] <0.173.0> CRASH REPORT Process <0.173.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Logger.WatcherSupervisor',{'EXIT',{{badmatch,{error,{{{case_clause,{'EXIT',{function_clause,[{'Elixir.LagerBackend',init,[[]],[{file,"lib/lager_backend.ex"},{line,12}]},{'Elixir.LagerBackend',init,1,[{file,"lib/lager_backend.ex"},{line,24}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},[{'Elixir.Logger.Watcher',...},...]},...}}},...}}}},...} in application_master:init/4 line 134
2018-03-04 13:55:46.721 [error] <0.180.0>@Elixir.ExUnit.CaptureServer:handle_call:47 gen_server 'Elixir.ExUnit.CaptureServer' terminated with reason: bad argument in call to erlang:unregister(capture_prompt) in 'Elixir.ExUnit.CaptureServer':handle_call/3 line 47
2018-03-04 13:56:56.370 [error] <0.180.0>@Elixir.ExUnit.CaptureServer:handle_call:47 gen_server 'Elixir.ExUnit.CaptureServer' terminated with reason: bad argument in call to erlang:unregister('Elixir.LagerBackend') in 'Elixir.ExUnit.CaptureServer':handle_call/3 line 47
2018-03-04 16:14:50.925 [error] <0.208.0>@Elixir.LagerLogBackendTest:test greets the world/1:9 error - module=LagerLogBackendTest 
2018-03-04 16:15:16.514 [error] <0.235.0>@Elixir.LagerLogBackendTest:test greets the world/1:9 error - module=LagerLogBackendTest 
2018-03-04 16:16:53.821 [error] <0.208.0>@Elixir.LagerLogBackendTest:test greets the world/1:9 error - module=LagerLogBackendTest 
2018-03-04 16:20:21.594 [error] <0.208.0>@Elixir.LagerLogBackendTest:test greets the world/1:10 error - module=LagerLogBackendTest 
2018-03-04 16:20:50.146 [error] <0.208.0>@Elixir.LagerLogBackendTest:test greets the world/1:10 error - module=LagerLogBackendTest 
2018-03-04 16:22:35.795 [error] <0.217.0>@Elixir.LagerLogBackendTest:test greets the world/1:10 error - module=LagerLogBackendTest 
2018-03-04 16:27:23.664 [error] <0.217.0>@Elixir.LagerLogBackendTest:test greets the world/1:10 error - module=LagerLogBackendTest 
2018-03-04 16:40:15.710 [error] <0.199.0>@Elixir.Logger.Watcher:init:25 CRASH REPORT Process <0.199.0> with 0 neighbours crashed with reason: no case clause matching {'EXIT',{undef,[{'Elixir.LagerLogBackend',init,['Elixir.LagerLogBackend'],[]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in 'Elixir.Logger.Watcher':init/1 line 25
2018-03-04 16:40:15.710 [error] <0.195.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.WatcherSupervisor' started with 'Elixir.Logger.WatcherSupervisor':start_link({'Elixir.Logger.Config',handlers,[]}) at undefined exit with reason {'EXIT',{{badmatch,{error,{{{case_clause,{'EXIT',{undef,[{'Elixir.LagerLogBackend',init,['Elixir.LagerLogBackend'],[]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},[{'Elixir.Logger.Watcher',init,1,[{file,"lib/logger/watcher.ex"},{line,25}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,init_it,6,[{file,"gen_serve..."},...]},...]},...}}},...}} in context start_error
2018-03-04 16:40:15.710 [error] <0.193.0> CRASH REPORT Process <0.193.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Logger.WatcherSupervisor',{'EXIT',{{badmatch,{error,{{{case_clause,{'EXIT',{undef,[{'Elixir.LagerLogBackend',init,['Elixir.LagerLogBackend'],[]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},[{'Elixir.Logger.Watcher',init,1,[{file,"lib/logger/watcher.ex"},{line,25}]},{gen_server,init_it,2,[{file,"..."},...]},...]},...}}},...}}}},...} in application_master:init/4 line 134
2018-03-04 16:41:37.380 [error] <0.235.0>@Elixir.LogLagerBackendTest:test greets the world/1:10 error - module=LogLagerBackendTest 
2018-03-04 16:46:02.804 [error] <0.208.0>@Elixir.LogLagerBackendTest:test greets the world/1:10 error - module=LogLagerBackendTest 
2018-03-04 16:56:00.627 [error] <0.1116.0>@Elixir.LogLagerBackendTest:test greets the world/1:10 error - module=LogLagerBackendTest 
2018-03-04 16:58:42.812 [error] <0.236.0>@Elixir.Logger.Watcher:init:25 CRASH REPORT Process <0.236.0> with 0 neighbours crashed with reason: no case clause matching {'EXIT',{function_clause,[{'Elixir.Keyword',merge,[nil,[]],[{file,"lib/keyword.ex"},{line,673}]},{'Elixir.LogLagerBackend',init,1,[{file,"lib/log_lager_backend.ex"},{line,18}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in 'Elixir.Logger.Watcher':init/1 line 25
2018-03-04 17:00:58.944 [error] <0.209.0>@Elixir.Logger.Watcher:init:25 CRASH REPORT Process <0.209.0> with 0 neighbours crashed with reason: no case clause matching {'EXIT',{function_clause,[{'Elixir.Keyword',merge,[nil,[]],[{file,"lib/keyword.ex"},{line,673}]},{'Elixir.LogLagerBackend',init,1,[{file,"lib/log_lager_backend.ex"},{line,18}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in 'Elixir.Logger.Watcher':init/1 line 25
2018-03-04 17:03:13.956 [error] <0.218.0>@Elixir.Logger.Watcher:init:25 CRASH REPORT Process <0.218.0> with 0 neighbours crashed with reason: no case clause matching {'EXIT',{function_clause,[{'Elixir.Keyword',merge,[nil,[]],[{file,"lib/keyword.ex"},{line,673}]},{'Elixir.LogLagerBackend',init,1,[{file,"lib/log_lager_backend.ex"},{line,18}]},{gen_event,server_add_handler,4,[{file,"gen_event.erl"},{line,469}]},{gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,314}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in 'Elixir.Logger.Watcher':init/1 line 25
2018-03-04 17:05:34.376 [error] <0.217.0>@Elixir.LogLagerBackendTest:test greets the world/1:16 
17:05:34.376 [error] error

2018-03-04 17:05:56.532 [error] <0.208.0>@Elixir.LogLagerBackendTest:test greets the world/1:16 error - 

2018-03-04 17:07:08.305 [error] <0.208.0>@Elixir.LogLagerBackendTest:test greets the world/1:18 error - module=LogLagerBackendTest 

2018-03-04 20:10:10.710 [error] <0.1116.0>@Elixir.LogLagerBackendTest:test greets the world/1:18 error - module=LogLagerBackendTest 

